### ISSUE TITLE
: or \ character at value section of a YML

### ISSUE THREAD

**Issue by farukdemirel** [joao-m-costa/delphi-yaml-to-json#1]
Hi, I tried to convert a sigma rule yml file to json with your library, almost ok but if a 
":" (column) and \ (Backslash) exist in value part destroys JSON structure.

Example lines from test yml:

at this line the \ destroys the structure and should be escaped to fix.
...........
 SELECTION_4:
        NewProcessName: '*\SharpView.exe'
..........

The lines below have the : in values.
references:
- https://github.com/tevora-threat/SharpView/
- https://github.com/PowerShellMafia/PowerSploit/blob/dev/Recon/PowerView.ps1
- https://github.com/redcanaryco/atomic-red-team/blob/f339e7da7d05f6057fdfcdd3742bfcf3
[proc_creation_win_hktl_sharpview _yml.txt](https://github.com/joao-m-costa/delphi-yaml-to-json/files/10825492/proc_creation_win_hktl_sharpview._yml.txt)
65fee2a9/atomics/T1049/T1049.md#atomic-test-4---system-discovery-using-sharpview
related:
-   id: dcd74b95-3f36-4ed9-9598-0490951643aa
    type: similar

Attached the sample yml file but changed extension to txt.

[proc_creation_win_hktl_sharpview _yml.txt](https://github.com/joao-m-costa/delphi-yaml-to-json/files/10825510/proc_creation_win_hktl_sharpview._yml.txt)

**Comment by farukdemirel** [comment]
Sorry, the links above are actually content of the sample YML but they seems as link.

**Comment by joao-m-costa** [comment]
Fixed in last commit (15-03-2024)
